import static org.junit.Assert.*;
import org.junit.Test;
//This file is used to test the Goalkeeper.java file and check if
//it runs as intended(using JUnit).

public class GoalkeeperTest{
    @Test
    public void test_creation_defaultConstructor(){
        Goalkeeper g = new Goalkeeper();
        assertEquals("Expected initial player score to be 0", 0, g.getGoalkeeperScore());
    }
    @Test
    public void test_setter(){
        Goalkeeper g = new Goalkeeper();
        g.setName("Mickey");
        g.setNationality("Georgia");
        assertEquals("Changed goalkeeper name is 'Mickey' from a default value ", "Mickey", g.getName());
        assertEquals("Changed goalkeeper nationality is 'Georgia' from a default value ", "Georgia", g.getNationality());
    }
    @Test
    public void test_getter(){
        Goalkeeper g = new Goalkeeper("FirstName","FirstNat");
        assertEquals("Expected goalkeeper name to be 'FirstName'", "FirstName", g.getName());
        assertEquals("Expected goalkeeper nationality to be 'FirstNat'", "FirstNat", g.getNationality());
    }
    @Test
    public void test_constructor_setter_AND_getter(){
        Goalkeeper g = new Goalkeeper("InitialName","InitialNat");
        g.setName("NewName");
        g.setNationality("NewNat");
        assertEquals("Changed goalkeeper name is 'NewName' from 'InitialName'", "NewName", g.getName());
        assertEquals("Changed goalkeeper name is 'NewNat' from 'InitialNat'", "NewNat", g.getNationality());
    }
    @Test
    public void test_valid_goalkeeperScore(){
        Goalkeeper g = new Goalkeeper("TestName","TestNat");
        g.setGoalkeeperScore(9);
        assertEquals("Set goalkeeper score to be 9. Expected 9.",9,g.getGoalkeeperScore());
    }
    @Test
    public void test_invalid_goalkeeperScore(){
        Goalkeeper g = new Goalkeeper("TestName","TestNat");
        g.setGoalkeeperScore(-99);
        assertEquals("Expected default goalkeeper score of 0.",0,g.getGoalkeeperScore());
    }
    @Test
    public void test_gk_range(){
        Goalkeeper g = new Goalkeeper();
        int experimental = g.randGoalkeeperNum();
        boolean theoretical = (experimental>=1 && experimental<=6);
        assertEquals("Testing if random number generated by GK to choose direction to dive is between 1 and 6.",true,theoretical);
        
    }
}
